In [ ]:
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from math import sqrt

In [ ]:
housing = pd.read_csv('Housing.csv')

In [ ]:
housing.head(10)

,CRIM,ZN,INDUS,RIVER,NOX,RM,AGE,DIS,RAD,TAX,PRATIO,LSTAT,MEDV
0,3.32105,0.0,19.58,Yes,0.871,5.403,100.0,1.3216,5,403,14.7,26.82,13.4
1,1.12658,0.0,19.58,Yes,0.871,5.012,88.0,1.6102,5,403,14.7,12.12,15.3
2,1.41385,0.0,19.58,Yes,0.871,6.129,96.0,1.7494,5,403,14.7,15.12,17.0
3,3.53501,0.0,19.58,Yes,0.871,6.152,82.6,1.7455,5,403,14.7,15.02,15.6
4,1.27346,0.0,19.58,Yes,0.605,6.250,92.6,1.7984,5,403,14.7,5.50,27.0
5,1.83377,0.0,19.58,Yes,0.605,7.802,98.2,2.0407,5,403,14.7,1.92,50.0
6,1.51902,0.0,19.58,Yes,0.605,8.375,93.9,2.1620,5,403,14.7,3.32,50.0
7,0.13587,0.0,10.59,Yes,0.489,6.064,59.1,4.2392,4,277,18.6,14.66,24.4
8,0.43571,0.0,10.59,Yes,0.489,5.344,100.0,3.8750,4,277,18.6,23.09,20.0
9,0.17446,0.0,10.59,Yes,0.489,5.960,92.1,3.8771,4,277,18.6,17.27,21.7

In [ ]:
housing = pd.concat([housing, pd.get_dummies(housing['RIVER'], prefix='RIVER', drop_first=True)], axis=1)
housing.drop(['RIVER'], inplace=True, axis=1)

housing.head(5)

,CRIM,ZN,INDUS,NOX,RM,AGE,DIS,RAD,TAX,PRATIO,LSTAT,MEDV,RIVER_Yes
0,3.32105,0.0,19.58,0.871,5.403,100.0,1.3216,5,403,14.7,26.82,13.4,True
1,1.12658,0.0,19.58,0.871,5.012,88.0,1.6102,5,403,14.7,12.12,15.3,True
2,1.41385,0.0,19.58,0.871,6.129,96.0,1.7494,5,403,14.7,15.12,17.0,True
3,3.53501,0.0,19.58,0.871,6.152,82.6,1.7455,5,403,14.7,15.02,15.6,True
4,1.27346,0.0,19.58,0.605,6.250,92.6,1.7984,5,403,14.7,5.50,27.0,True

In [ ]:
model = smf.ols(formula='MEDV ~ CRIM + ZN + INDUS + NOX + RM + AGE + DIS + RAD + TAX + PRATIO + LSTAT + RIVER_Yes', data=housing)
result = model.fit()

In [ ]:
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   MEDV   R-squared:                       0.734
Model:                            OLS   Adj. R-squared:                  0.728
Method:                 Least Squares   F-statistic:                     113.5
Date:                Wed, 13 May 2026   Prob (F-statistic):          2.23e-133
Time:                        00:27:45   Log-Likelihood:                -1504.9
No. Observations:                 506   AIC:                             3036.
Df Residuals:                     493   BIC:                             3091.
Df Model:                          12
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept            41.6173      4.936      8.431      0.000      31.919      51.316
RIVER_Yes[T.True]     2.8400      0.870      3.264      0.001       1.131       4.549
CRIM                 -0.1214      0.033     -3.678      0.000      -0.186      -0.057
ZN                    0.0470      0.014      3.384      0.001       0.020       0.074
INDUS                 0.0135      0.062      0.217      0.829      -0.109       0.136
NOX                 -18.7580      3.851     -4.870      0.000     -26.325     -11.191
RM                    3.6581      0.420      8.705      0.000       2.832       4.484
AGE                   0.0036      0.013      0.271      0.787      -0.023       0.030
DIS                  -1.4908      0.202     -7.394      0.000      -1.887      -1.095
RAD                   0.2894      0.067      4.325      0.000       0.158       0.421
TAX                  -0.0127      0.004     -3.337      0.001      -0.020      -0.005
PRATIO               -0.9375      0.132     -7.091      0.000      -1.197      -0.678
LSTAT                -0.5520      0.051    -10.897      0.000      -0.652      -0.452
==============================================================================
Omnibus:                      171.096   Durbin-Watson:                   1.168
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              709.937
Skew:                           1.477   Prob(JB):                    6.90e-155
Kurtosis:                       7.995   Cond. No.                     1.17e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.17e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
feature_names = list(['CRIM', 'ZN', 'INDUS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PRATIO', 'LSTAT', 'RIVER_Yes'])
housing_features = housing[feature_names]

target_name = list(['MEDV'])
housing_target = housing[target_name]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(housing_features,housing_target, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(404, 12)
(102, 12)
(404, 1)
(102, 1)

In [ ]:
regressor = LinearRegression(fit_intercept = True)
regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_train_pred = regressor.predict(X_train)
y_test_pred = regressor.predict(X_test)

In [ ]:
print('RMSE train: %.3f, test: %.3f' % (
        sqrt(mean_squared_error(y_train, y_train_pred)),
        sqrt(mean_squared_error(y_test, y_test_pred))))
print('R^2 train: %.3f, test: %.3f' % (
        r2_score(y_train, y_train_pred),
        r2_score(y_test, y_test_pred)))

RMSE train: 4.574, test: 5.384
R^2 train: 0.747, test: 0.684

In [ ]:
print("Coefficients:\n", regressor.coef_)
print("Intercept:\n", regressor.intercept_)

Coefficients:
 [[-1.27602565e-01  4.62298207e-02 -5.10691067e-03 -1.54465024e+01
   3.80864472e+00  7.01507805e-03 -1.39215520e+00  2.37284247e-01
  -1.08450209e-02 -9.68409524e-01 -5.46033184e-01  2.89693965e+00]]
Intercept:
 [38.62324864]

In [ ]:
prediction = regressor.predict([[3.32105, 0.0, 19.58, 0.871, 5.403, 100.0, 1.3216, 5, 403, 14.7, 26.82, 1]])
print('Prediction:', prediction)

#Correct answer should be 13.4

Prediction: [[14.91790762]]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
prediction2 = regressor.predict([[1.38799, 0, 8.14, 0.538, 5.95, 82, 3.99, 4, 307, 21, 27.71, 0]])
print('Prediction:', prediction2)

#Correct answer should be 13.2

Prediction: [[9.92885827]]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
prediction3 = regressor.predict([[0.01311, 90, 1.22, 0.403, 7.249, 21.9, 8.6966, 5, 226, 17.9, 4.81, 0]])
print('Prediction:', prediction3)

#Correct answer should be 35.4

Prediction: [[30.98106398]]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
prediction4 = regressor.predict([[4.1, 9.84, 12.11, 0.55, 5.92, 55, 2.11, 10, 311, 20, 15, 1]])
print('Prediction:', prediction4)

Prediction: [[24.33140948]]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
print(housing['RM'].max())
print(housing['RM'].min())

print(housing['NOX'].max())
print(housing['NOX'].min())

print(housing['MEDV'].max())
print(housing['MEDV'].min())

print("Max values:", housing.max())
print("Min values:", housing.min())
print("Mean values:", housing.mean())

8.78
3.561
0.871
0.385
50.0
5.0
Max values: CRIM         88.9762
ZN             100.0
INDUS          27.74
NOX            0.871
RM              8.78
AGE            100.0
DIS          12.1265
RAD               24
TAX              711
PRATIO          22.0
LSTAT          37.97
MEDV            50.0
RIVER_Yes       True
dtype: object
Min values: CRIM         0.00632
ZN               0.0
INDUS           0.46
NOX            0.385
RM             3.561
AGE              2.9
DIS           1.1296
RAD                1
TAX              187
PRATIO          12.6
LSTAT           1.73
MEDV             5.0
RIVER_Yes      False
dtype: object
Mean values: CRIM           3.613524
ZN            11.363636
INDUS         11.136779
NOX            0.554695
RM             6.284634
AGE           68.574901
DIS            3.795043
RAD            9.549407
TAX          408.237154
PRATIO        18.455534
LSTAT         12.653063
MEDV          22.532806
RIVER_Yes      0.069170
dtype: float64